[package]
name = "hyprland-minimize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyprland = "0.3.9"
serde = "1.0.183"
serde_json = "1.0.104"
